CREATE TABLE recipes (
    id UUID PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    pizza_count INTEGER NOT NULL,
    dough_ball_weight_grams NUMERIC NOT NULL,
    hydration_percent NUMERIC NOT NULL,
    salt_percent NUMERIC NOT NULL,
    yeast_type VARCHAR(40) NOT NULL,
    dough_method VARCHAR(40) NOT NULL,
    fermentation_preset VARCHAR(80),
    fermentation_schedule_mode VARCHAR(40),
    fermentation_schedule_room_hours NUMERIC,
    fermentation_schedule_cold_hours NUMERIC,
    fermentation_schedule_room_temperature_celsius NUMERIC,
    fermentation_schedule_cold_temperature_celsius NUMERIC,
    room_temperature_celsius NUMERIC,
    cold_temperature_celsius NUMERIC,
    preferment_flour_percent NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
